
ENCODING = 'iso-8859-15'

LANGUAGES = {}

LANGUAGES['en'] = [
    "Arabic" ,
    "Chinese",
    "Croatian",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "Finnish",
    "French",
    "German",
    "Hindi",
    "Italian",
    "Japanese",
    "Korean",
    "Latin",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Russian",
    "Slovak",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Turkish"
]

LANGUAGES['es'] = [
    "Árabe",
    "Chino",
    "Croata",
    "Checo",
    "Danés",
    "Holandes",
    "Inglés",
    "Finés",
    "Francés",
    "Alemán",
    "Indio",
    "Italiano",
    "Japonés",
    "Koreano",
    "Latin",
    "Noruego",
    "Polaco",
    "Portugués",
    "Rumano",
    "Ruso",
    "Eslovaco",
    "Esloveno",
    "Español",
    "Sueco",
    "Turco"
]

EDITIONS = [
    "[SC]-Songs",
    "Band Hero",
    "Disney Sing It",
    "Disney Sing It Family Hits",
    "Disney Sing It Pop Hits",
    "Disney Sing It! High School Musical 3",
    "Green Day Rock Band",
    "Guitar Hero 5",
    "Guitar Hero Greatest Hits",
    "Guitar Hero Metallica",
    "Guitar Hero Warriors of Rock",
    "Guitar Hero World Tour",
    "Lego Rock Band",
    "Rock Band",
    "Rock Band 2",
    "Rock Band 3",
    "Rock Band Country Track Pack",
    "Rock Band Europe",
    "Rock Band Store 2007",
    "Rock Band Store 2008 Vol. 1",
    "Rock Band Store 2008 Vol. 2",
    "Rock Band Store 2008 Vol. 3",
    "Rock Band Store 2008 Vol. 4",
    "Rock Band Store 2009 Vol. 1",
    "Rock Band Store 2009 Vol. 2",
    "Rock Band Store 2009 Vol. 3",
    "Rock Band Store 2009 Vol. 4",
    "Rock Band Store 2010 Vol. 1",
    "Rock Band Store 2010 Vol. 3",
    "Rock Band Store 2010 Vol. 4",
    "Rock Band Store 2011 Vol. 1",
    "Rock Band Store 2011 Vol. 2",
    "Rock Band Store 2011 Vol. 3",
    "Rock Band Store 2011 Vol. 4",
    "Rock Band Track Pack AC/DC Live",
    "Rock Band Track Pack Classic Rock",
    "Rock Band Track Pack Vol. 1",
    "Rock Band Track Pack Vol. 2",
    "Rock Band Wii",
    "SingStar",
    "SingStar ’80s",
    "SingStar ’80s Dutch",
    "SingStar ’80s French",
    "SingStar ’80s German",
    "SingStar ’80s Italian",
    "SingStar ’80s Polish",
    "SingStar ’80s Swedish",
    "SingStar ’80s USA",
    "SingStar ’90s",
    "SingStar ’90s USA",
    "SingStar ABBA",
    "SingStar Amped",
    "SingStar Amped Australian",
    "SingStar Amped German",
    "SingStar Amped USA",
    "SingStar Anthems",
    "SingStar Après-Ski Party",
    "SingStar Après-Ski Party 2",
    "SingStar Back to the ’80s",
    "SingStar best of Disney",
    "SingStar Bollywood",
    "SingStar Boy Bands vs Girl Bands",
    "SingStar Canções Disney",
    "SingStar Canciones Disney",
    "SingStar Chansons magiques de Disney",
    "SingStar Chart Hits",
    "SingStar Chartbreaker",
    "SingStar Clásicos",
    "SingStar Country",
    "SingStar Deutsch Music",
    "SingStar Deutsch Rock-Pop",
    "SingStar Deutsch Rock-Pop Vol. 2",
    "SingStar Die größten Solokünstler",
    "SingStar Die Toten Hosen",
    "SingStar e la magia Disney",
    "SingStar English",
    "SingStar ESKA Hity Na Czasie",
    "SingStar French",
    "SingStar Fußballhits",
    "SingStar German",
    "SingStar Hottest Hits",
    "SingStar Hottest Hits German",
    "SingStar Hottest Hits UK",
    "SingStar Italian",
    "SingStar Italian Greatest Hits",
    "SingStar Italian Party",
    "SingStar Italian Party 2",
    "SingStar La Edad de Oro del Pop Español",
    "SingStar Latino",
    "SingStar Latino Spanish",
    "SingStar Latino Portuguese",
    "SingStar Legendat",
    "SingStar Legends",
    "SingStar Legends Australian",
    "SingStar Legends Danish",
    "SingStar Legends French",
    "SingStar Legends German",
    "SingStar Legends Italian",
    "SingStar Legends USA",
    "SingStar Legends UK",
    "SingStar Made in Germany",
    "SingStar Mallorca Party",
    "SingStar Mecano",
    "SingStar Miliki",
    "SingStar Morangos com Açucar",
    "SingStar Motown",
    "SingStar Norsk På Norsk",
    "SingStar Norske Hits",
    "SingStar NRJ Music Tour",
    "SingStar Operación Triunfo",
    "SingStar Party",
    "SingStar Party UK",
    "SingStar Party German",
    "SingStar Party Hits",
    "SingStar Party Italian",
    "SingStar Patito Feo",
    "SingStar Polskie Hity",
    "SingStar Polskie Hity 2",
    "SingStar Pop",
    "SingStar Pop Edition (PS3)",
    "SingStar Popworld",
    "SingStar The Dome",
    "SingStar Pop 2",
    "SingStar Pop 2009",
    "SingStar Pop Australian",
    "SingStar Pop Hits",
    "SingStar Pop Hits 2",
    "SingStar Pop Hits 3",
    "SingStar Pop Hits 4",
    "SingStar Pop Hits Australian",
    "SingStar Pop Hits 40 Principales",
    "SingStar Pop Hits French",
    "SingStar Pop Hits German",
    "SingStar Pop Hits Portuguese",
    "SingStar Pop Hits Skandinavisk",
    "SingStar Pop Hits UK",
    "SingStar Pop USA",
    "SingStar Pop Vol. 2",
    "SingStar Popworld",
    "SingStar Portugal Hits",
    "SingStar Queen",
    "SingStar R&B Polish",
    "SingStar R&B",
    "SingStar Radio 105",
    "SingStar Rock Ballads",
    "SingStar Rock Music",
    "SingStar Rocks!",
    "SingStar Rocks! Australian",
    "SingStar Rocks! UK",
    "SingStar Rocks! French",
    "SingStar Rocks! HRVATSKA!",
    "SingStar Rocks! TMF",
    "SingStar Rocks! USA",
    "SingStar Russian Hits",
    "SingStar Schlager",
    "SingStar Singalong with Disney",
    "SingStar sjung med Disney",
    "SingStar Summer Party",
    "SingStar Summer Party Danish",
    "SingStar Summer Party English",
    "SingStar Summer Party German",
    "SingStar Summer Party Portuguese",
    "SingStar Summer Party UK",
    "SingStar Summer Party German",
    "SingStar Party Hits Australian",
    "SingStar SuomiPop",
    "SingStar SuomiRock",
    "SingStar Svenska Hits",
    "SingStar Svenska Hits Schlager",
    "SingStar Svenska Stjarnor",
    "SingStar Take That",
    "SingStar The Dome",
    "SingStar The Wiggles",
    "SingStar top.it",
    "SingStar Turkish Party",
    "SingStar Vasco",
    "SingStar German",
    "SingStar UK",
    "SingStar Ultimate Party",
    "SingStar Wakacyjna Impreza!",
    "Sin Edición"
]

GENRES = [
    "A capella",
    "Acid",
    "Acid Jazz",
    "Acid Punk",
    "Acoustic",
    "AlternRock",
    "Alternative",
    "Ambient",
    "Avantgarde",
    "Ballad",
    "Bass",
    "Bebob",
    "Big Band",
    "Bluegrass",
    "Blues",
    "Booty Bass",
    "Cabaret",
    "Celtic",
    "Chamber Music",
    "Chanson",
    "Chorus",
    "Christian Rap",
    "Classic Rock",
    "Classical",
    "Club",
    "Comedy",
    "Country",
    "Cult",
    "Dance",
    "Dance Hall",
    "Darkwave",
    "Death Metal",
    "Disco",
    "Dream",
    "Duet",
    "Easy Listening",
    "Electronic",
    "Ethnic",
    "Euro-House",
    "Euro-Techno",
    "Eurodance",
    "Fast Fusion",
    "Folk",
    "Folk-Rock",
    "Folklore",
    "Freestyle",
    "Funk",
    "Fusion",
    "Game",
    "Gangsta",
    "Gospel",
    "Gothic",
    "Gothic Rock",
    "Grunge",
    "Hard Rock",
    "Hip-Hop",
    "House",
    "Humour",
    "Industrial",
    "Instrumental",
    "Instrumental Pop",
    "Instrumental Rock",
    "Jazz",
    "Jazz+Funk",
    "Jungle",
    "Latin",
    "Lo-Fi",
    "Meditative",
    "Metal",
    "Musical",
    "National Folk",
    "Native American",
    "New Age",
    "New Wave",
    "Noise",
    "Oldies",
    "Opera",
    "Other",
    "Polka",
    "Pop",
    "Pop-Folk",
    "Pop/Funk",
    "Porn Groove",
    "Power Ballad",
    "Pranks",
    "Primus",
    "Progressive Rock",
    "Psychadelic",
    "Psychedelic Rock",
    "Punk",
    "Punk Rock",
    "R&B",
    "Rap",
    "Rave",
    "Reggae",
    "Retro",
    "Revival",
    "Rhythmic Soul",
    "Rock",
    "Rock & Roll",
    "Samba",
    "Satire",
    "Schlager",
    "Showtunes",
    "Ska",
    "Slow Jam",
    "Slow Rock",
    "Sonata",
    "Soul",
    "Sound Clip",
    "Soundtrack",
    "Southern Rock",
    "Space",
    "Speech",
    "Swing",
    "Symphonic Rock",
    "Symphony",
    "Tango",
    "Techno",
    "Techno-Industrial",
    "Top",
    "Trailer",
    "Trance",
    "Tribal",
    "Trip-Hop",
    "Vocal",
    "Reggaeton",
    "Trap"
]

TAGS = [
    "ENCODING",
    "TITLE",
    "ARTIST",
    "LANGUAGE",
    "EDITION",
    "GENRE",
    "YEAR",
    "CREATOR",
    "MP3",
    "COVER",
    "BACKGROUND",
    "VIDEO",
    "VIDEOGAP",
    "START",
    "END",
    "RELATIVE",
    "PREVIEWSTART",
    "CALCMEDLEY",
    "MEDLEYSTARTBEAT",
    "MEDLEYENDBEAT",
    "BPM",
    "GAP",
    "P1",
    "P2",
    "ALBUM",
    "COMMENT",
    "SOURCE",
    "ARTIST-ON-SORTING",
    "TITLE-ON-SORTING"
]